apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
  namespace: kub-7
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi